jobs:
  - job: ubuntu_16_04
    displayName: 'Build - Ubuntu 16.04'
    continueOnError: false
    pool:
      vmImage: 'Ubuntu 16.04'
    container:
      image: lganzzzo/ubuntu-cmake:latest
    workspace:
      clean: all
    steps:
      - script: |
          sudo ./prepare.sh
        displayName: 'prepare.sh'
      - script: |
          cmake ..
          sudo make
          make test ARGS="-V"
        workingDirectory: server/build
        displayName: 'build server'
      - script: |
          cmake ..
          sudo make
          make test ARGS="-V"
        workingDirectory: client/build
        displayName: 'build client'
