jobs:
  - job: ubuntu_20_04
    displayName: 'Build - Ubuntu 20.04'
    continueOnError: false
    pool:
      vmImage: 'ubuntu-20.04'
    container:
      image: lganzzzo/ubuntu-cmake:latest
    workspace:
      clean: all
    steps:
      - script: |
          sudo ./prepare.sh
        displayName: 'prepare.sh'
      - script: |
          sudo cmake ..
          sudo make
          make test ARGS="-V"
        workingDirectory: server/build
        displayName: 'build server'
      - script: |
          sudo cmake ..
          sudo make
          make test ARGS="-V"
        workingDirectory: client/build
        displayName: 'build client'
